2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "version" not found; SQL statement:
SELECT next_update FROM version [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "account" not found; SQL statement:
truncate table "account" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "account_asset" not found; SQL statement:
truncate table "account_asset" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "alias" not found; SQL statement:
truncate table "alias" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "alias_offer" not found; SQL statement:
truncate table "alias_offer" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ask_order" not found; SQL statement:
truncate table "ask_order" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "asset" not found; SQL statement:
truncate table "asset" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "asset_transfer" not found; SQL statement:
truncate table "asset_transfer" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "at" not found; SQL statement:
truncate table "at" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "at_state" not found; SQL statement:
truncate table "at_state" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "bid_order" not found; SQL statement:
truncate table "bid_order" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot truncate "PUBLIC.""block"""; SQL statement:
truncate table "block" [90106-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.TruncateTable.update(TruncateTable.java:35)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:207)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:429)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
	at brs.db.sql.SqlBlockDb.deleteAll(SqlBlockDb.java:221)
	at brs.db.h2.H2DbVersion.update(H2DbVersion.java:224)
	at brs.db.h2.H2DbVersion.init(H2DbVersion.java:39)
	at brs.db.h2.H2Dbs.<init>(H2Dbs.java:23)
	at brs.db.sql.Db.getDbsByDatabaseType(Db.java:122)
	at brs.Burst.loadWallet(Burst.java:200)
	at brs.Burst.init(Burst.java:179)
	at brs.Burst.main(Burst.java:160)
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "escrow" not found; SQL statement:
truncate table "escrow" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "escrow_decision" not found; SQL statement:
truncate table "escrow_decision" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "goods" not found; SQL statement:
truncate table "goods" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "purchase" not found; SQL statement:
truncate table "purchase" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "purchase_feedback" not found; SQL statement:
truncate table "purchase_feedback" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "purchase_public_feedback" not found; SQL statement:
truncate table "purchase_public_feedback" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "reward_recip_assign" not found; SQL statement:
truncate table "reward_recip_assign" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "subscription" not found; SQL statement:
truncate table "subscription" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "trade" not found; SQL statement:
truncate table "trade" [42102-196]
2018-05-07 18:51:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "unconfirmed_transaction" not found; SQL statement:
truncate table "unconfirmed_transaction" [42102-196]
2018-05-07 18:53:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1484)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1459)
	at org.h2.jdbc.JdbcConnection.clearWarnings(JdbcConnection.java:645)
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:250)
	at brs.db.sql.Db.shutdown(Db.java:150)
	at brs.Burst.shutdown(Burst.java:314)
	at brs.Burst.shutdown(Burst.java:303)
	at java.lang.Thread.run(Thread.java:748)
2018-05-07 18:59:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1484)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1459)
	at org.h2.jdbc.JdbcConnection.clearWarnings(JdbcConnection.java:645)
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:250)
	at brs.db.sql.Db.shutdown(Db.java:150)
	at brs.Burst.shutdown(Burst.java:314)
	at brs.Burst.shutdown(Burst.java:303)
	at java.lang.Thread.run(Thread.java:748)
2018-05-07 19:03:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1484)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1459)
	at org.h2.jdbc.JdbcConnection.clearWarnings(JdbcConnection.java:645)
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:250)
	at brs.db.sql.Db.shutdown(Db.java:150)
	at brs.Burst.shutdown(Burst.java:314)
	at brs.Burst.shutdown(Burst.java:303)
	at java.lang.Thread.run(Thread.java:748)
2018-05-07 19:08:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1484)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1459)
	at org.h2.jdbc.JdbcConnection.clearWarnings(JdbcConnection.java:645)
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:250)
	at brs.db.sql.Db.shutdown(Db.java:150)
	at brs.Burst.shutdown(Burst.java:314)
	at brs.Burst.shutdown(Burst.java:303)
	at java.lang.Thread.run(Thread.java:748)
2018-05-07 20:03:32 jdbc[33]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1484)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1459)
	at org.h2.jdbc.JdbcConnection.clearWarnings(JdbcConnection.java:645)
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:250)
	at brs.db.sql.Db.shutdown(Db.java:150)
	at brs.Burst.shutdown(Burst.java:312)
	at brs.Burst.shutdown(Burst.java:301)
	at java.lang.Thread.run(Thread.java:748)
